[profile.default]
src = "src"
out = "out"
# contracts in libs are excluded from code coverage reports
libs = ["lib", 'src/external']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
